Repository kolplattformen/skolplattformen, pull requests merged in 2021-05, with the labels that each got.

#362 Hyphenation issues
  packages/app/components/absence.component.tsx
  packages/app/components/child.component.tsx
  packages/app/components/children.component.tsx
  packages/app/components/newsItem.component.tsx
  packages/app/components/saveToCalendar.component.tsx
  packages/app/components/week.component.tsx
Labels: tillgänglighet

#390 fix: 🐛 add a11y lint and fix errors
  packages/app/.eslintrc.json
  packages/app/components/absence.component.tsx
  packages/app/components/auth.component.tsx
  packages/app/components/childListItem.component.tsx
  packages/app/components/children.component.tsx
  packages/app/components/contactMenu.component.tsx
  packages/app/components/image.component.tsx
  packages/app/components/login.component.tsx
  packages/app/components/markdown.component.tsx
  packages/app/components/menu.component.tsx
  packages/app/components/newsItem.component.tsx
  packages/app/components/newsList.component.tsx
  packages/app/components/newsListItem.component.tsx
  packages/app/components/saveToCalendar.component.tsx
  packages/app/package.json
  packages/app/translations/en.json
  packages/app/translations/sv.json
  packages/app/yarn.lock
Labels: tillgänglighet

#393 feat(site): dark mode
  packages/site/assets/img/boys.png
  packages/site/assets/img/girls.png
  packages/site/components/Banner.tsx
  packages/site/components/ButtonLink.tsx
  packages/site/components/CtaThree.tsx
  packages/site/components/FeatureCard.tsx
  packages/site/components/Footer.tsx
  packages/site/components/FunFacts.tsx
  packages/site/components/Header.tsx
  packages/site/components/Link.tsx
  packages/site/components/NavLinks.tsx
  packages/site/components/PricingTemp.tsx
  packages/site/components/Privacy.tsx
  packages/site/components/QA.tsx
  packages/site/components/Section.tsx
  packages/site/components/SectionTitle.tsx
  packages/site/components/Status.tsx
  packages/site/components/Testimonials.tsx
  packages/site/components/Timeline.tsx
  packages/site/components/TimelineLatest.tsx
  packages/site/components/Typography.tsx
  packages/site/pages/aktuellt.tsx
  packages/site/pages/index.tsx
  packages/site/pages/integritet.tsx
  packages/site/pages/qa.tsx
  packages/site/pages/status.tsx
  packages/site/styles/global.css
  packages/site/tailwind.config.js
Labels: förbättring

#396 fix(site): dark mode icons
  packages/site/assets/img/icons/goal.svg
  packages/site/assets/img/icons/planning.svg
  packages/site/assets/img/icons/play-arrow.svg
  packages/site/assets/img/icons/project-management.svg
  packages/site/assets/img/icons/solution.svg
  packages/site/assets/img/icons/solution1.svg
  packages/site/assets/img/icons/teamwork.svg
  packages/site/components/FeatureCard.tsx
  packages/site/components/Features.tsx
  packages/site/components/featureData.tsx
  packages/site/styles/global.css
Labels: förbättring

#395 Translations update from Weblate
  packages/app/translations/en.json
  packages/app/translations/es.json
  packages/app/translations/fi.json
  packages/app/translations/it.json
  packages/app/translations/la.json
  packages/app/translations/nb_NO.json
  packages/app/translations/nl.json
  packages/app/translations/pl.json
  packages/app/translations/so.json
Labels: Översättningar
